

-- #region pomodoros table

CREATE TYPE "public"."pomodoro_state" AS ENUM (
    'current',
    'paused',
    'finished',
    'skipped',
    'idle'
);

ALTER TYPE "public"."pomodoro_state" OWNER TO "postgres";

CREATE TYPE "public"."time_measurement_mode" AS ENUM ('pomodoro', 'flow');
ALTER TYPE "public"."time_measurement_mode" OWNER TO "postgres";


CREATE TYPE "public"."pomodoro_type" AS ENUM (
    'focus',
    'break',
    'long_break'
);

ALTER TYPE "public"."pomodoro_type" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pomodoros" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "started_at" timestamp with time zone DEFAULT NULL,
    "expected_end" timestamp with time zone,
    "timelapse" integer DEFAULT 0 NOT NULL,
    "user_id" "uuid" NOT NULL,
    "state" "public"."pomodoro_state" DEFAULT 'idle'::"public"."pomodoro_state" NOT NULL,
    "finished_at" timestamp with time zone,
    "toggle_timeline" "jsonb",
    "cycle" bigint,
    "time_session_id" bigint,
    "expected_duration" smallint DEFAULT '1500'::smallint NOT NULL,
    "type" "public"."pomodoro_type" DEFAULT 'focus'::"public"."pomodoro_type" NOT NULL
);

ALTER TABLE "public"."pomodoros" OWNER TO "postgres";
-- #endregion
-- #endregion

-- #region pomodoros_cycles table
CREATE TABLE IF NOT EXISTS "public"."pomodoros_cycles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "state" "public"."pomodoro_state",
    "user_id" "uuid",
    "required_tags" "text"[] DEFAULT '{focus,break,focus,long_break}'::"text"[]
);

ALTER TABLE "public"."pomodoros_cycles" OWNER TO "postgres";

ALTER TABLE "public"."pomodoros_cycles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pomodoros_cycles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
-- #endregion

-- #region pomodoros_tags table
CREATE TABLE IF NOT EXISTS "public"."pomodoros_tags" (
    "user_id" "uuid",
    "pomodoro" integer NOT NULL,
    "tag" integer NOT NULL
);


ALTER TABLE "public"."pomodoros_tags" OWNER TO "postgres";

-- #endregion


-- #region tags table
CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text",
    "label" "text" NOT NULL,
    "user_id" "uuid"
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
-- #endregion

-- #region tasks table
CREATE TYPE public.task_stage AS ENUM ('backlog', 'to_do', 'in_progress', 'done', 'archived');

CREATE TABLE IF NOT EXISTS "public"."tasks" (
    "id" "uuid" PRIMARY KEY DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "done" boolean DEFAULT false,
    "tag_id" integer,
    "pomodoro_id" integer,
    "archived" boolean DEFAULT false,
    "stage" public.task_stage DEFAULT 'backlog'::public.task_stage,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "done_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    "keep" boolean default false,
    "estimated_pomodoros" integer DEFAULT 1
);
ALTER TABLE "public"."tasks" OWNER TO "postgres";

-- #endregion

-- #region tasks_tags table
CREATE TABLE IF NOT EXISTS "public"."tasks_tags" (
    "user_id" "uuid",
    "task" "uuid" NOT NULL,
    "tag" integer NOT NULL
);
ALTER TABLE "public"."tasks_tags" OWNER TO "postgres";
-- #endregion

-- #endregion

-- #region profiles table
CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "username" "text",
    "fullname" "text",
    "avatar_url" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "has_password" boolean DEFAULT false,
    "settings" "jsonb"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";
-- #endregion

-- #region api_keys table
CREATE TABLE IF NOT EXISTS "public"."api_keys" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "api_keys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "api_keys_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."api_keys" OWNER TO "postgres";

-- #endregion






CREATE UNIQUE INDEX "profiles_username_idx" ON "public"."profiles" USING "btree" ("username");

CREATE UNIQUE INDEX "tags_label_system_idx" ON "public"."tags" USING "btree" ("label") WHERE ("user_id" IS NULL);

CREATE UNIQUE INDEX "tags_label_user_idx" ON "public"."tags" USING "btree" ("label", "user_id") WHERE ("user_id" IS NOT NULL);

CREATE UNIQUE INDEX "tags_type_system_idx" ON "public"."tags" USING "btree" ("type") WHERE ("user_id" IS NULL);



ALTER TABLE ONLY "public"."pomodoros_cycles"
    ADD CONSTRAINT "pomodoros_cycles_pkey" PRIMARY KEY ("id");






ALTER TABLE ONLY "public"."pomodoros_tags"
    ADD CONSTRAINT "pomodoros_tags_pkey" PRIMARY KEY ("tag", "pomodoro");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");





    

ALTER TABLE ONLY "public"."pomodoros_cycles"
    ADD CONSTRAINT "pomodoros_cycles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."pomodoros"
    ADD CONSTRAINT "pomodoros_cycle_fkey" FOREIGN KEY ("cycle") REFERENCES "public"."pomodoros_cycles"("id");



ALTER TABLE ONLY "public"."pomodoros_tags"
    ADD CONSTRAINT "pomodoros_tags_pomodoro_fkey" FOREIGN KEY ("pomodoro") REFERENCES "public"."pomodoros"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pomodoros_tags"
    ADD CONSTRAINT "pomodoros_tags_tag_fkey" FOREIGN KEY ("tag") REFERENCES "public"."tags"("id");



ALTER TABLE ONLY "public"."pomodoros_tags"
    ADD CONSTRAINT "pomodoros_tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");


ALTER TABLE ONLY "public"."tasks_tags"
    ADD CONSTRAINT "tasks_tags_pkey" PRIMARY KEY ("tag", "task");

ALTER TABLE ONLY "public"."tasks_tags"
    ADD CONSTRAINT "tasks_tags_task_fkey" FOREIGN KEY ("task") REFERENCES "public"."tasks"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tasks_tags"
    ADD CONSTRAINT "tasks_tags_tag_fkey" FOREIGN KEY ("tag") REFERENCES "public"."tags"("id");

ALTER TABLE ONLY "public"."tasks_tags"
    ADD CONSTRAINT "tasks_tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");


ALTER TABLE ONLY "public"."pomodoros"
    ADD CONSTRAINT "pomodoros_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pomodoro_id_fkey" FOREIGN KEY ("pomodoro_id") REFERENCES "public"."pomodoros"("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



GRANT ALL ON TABLE "public"."pomodoros" TO "anon";
GRANT ALL ON TABLE "public"."pomodoros" TO "authenticated";
GRANT ALL ON TABLE "public"."pomodoros" TO "service_role";

GRANT ALL ON TABLE "public"."pomodoros_cycles" TO "anon";
GRANT ALL ON TABLE "public"."pomodoros_cycles" TO "authenticated";
GRANT ALL ON TABLE "public"."pomodoros_cycles" TO "service_role";


GRANT ALL ON SEQUENCE "public"."pomodoros_cycles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pomodoros_cycles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pomodoros_cycles_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pomodoros_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pomodoros_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pomodoros_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pomodoros_tags" TO "anon";
GRANT ALL ON TABLE "public"."pomodoros_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."pomodoros_tags" TO "service_role";

GRANT ALL ON TABLE "public"."tasks_tags" TO "anon";
GRANT ALL ON TABLE "public"."tasks_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tasks_tags" TO "service_role";


GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tasks" TO "anon";
GRANT ALL ON TABLE "public"."tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."tasks" TO "service_role";

-- #region documents table
CREATE TABLE IF NOT EXISTS "public"."documents" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "content" text,
    "metadata" jsonb,
    "embedding" extensions.vector(768)
);
ALTER TABLE "public"."documents" OWNER TO "postgres";
-- #endregion

-- #region n8n_chat_histories table
CREATE TABLE IF NOT EXISTS "public"."n8n_chat_histories" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "session_id" character varying(255) NOT NULL,
    "message" jsonb NOT NULL
);
ALTER TABLE "public"."n8n_chat_histories" OWNER TO "postgres";
-- #endregion

-- #region push_subscriptions table
CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "subscription" jsonb NOT NULL,
    "user_agent" text,
    "device_info" jsonb,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "idx_push_subscriptions_user_id" ON "public"."push_subscriptions" USING btree ("user_id");
-- #endregion

-- #region user_secrets table
CREATE TABLE IF NOT EXISTS "public"."user_secrets" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "name" text NOT NULL,
    "key_value" text NOT NULL,
    "iv" text NOT NULL,
    "tag" text NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE ("user_id", "name")
);
ALTER TABLE "public"."user_secrets" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "idx_user_secrets_user_id" ON "public"."user_secrets" USING btree ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "user_secrets_user_id_name_key" ON "public"."user_secrets" USING "btree" ("user_id", "name");

-- #region Restored missing indexes from remote_schema.sql to prevent DROP migrations
CREATE INDEX IF NOT EXISTS "idx_api_keys_user_id" ON "public"."api_keys" USING "btree" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_pomodoros_cycle_id" ON "public"."pomodoros" USING "btree" ("cycle");
CREATE INDEX IF NOT EXISTS "idx_pomodoros_cycles_user_id" ON "public"."pomodoros_cycles" USING "btree" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_pomodoros_tags_pomodoro_id" ON "public"."pomodoros_tags" USING "btree" ("pomodoro");
CREATE INDEX IF NOT EXISTS "idx_pomodoros_tags_user_id" ON "public"."pomodoros_tags" USING "btree" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_pomodoros_user_id" ON "public"."pomodoros" USING "btree" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_tags_user_id" ON "public"."tags" USING "btree" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_pomodoro_id" ON "public"."tasks" USING "btree" ("pomodoro_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_tag_id" ON "public"."tasks" USING "btree" ("tag_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_tags_task_id" ON "public"."tasks_tags" USING "btree" ("task");
CREATE INDEX IF NOT EXISTS "idx_tasks_tags_user_id" ON "public"."tasks_tags" USING "btree" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_user_id" ON "public"."tasks" USING "btree" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_user_secrets_unique_name" ON "public"."user_secrets" USING "btree" ("user_id", "name");
CREATE INDEX IF NOT EXISTS "n8n_chat_histories_session_id_idx" ON "public"."n8n_chat_histories" USING "btree" ("session_id");
CREATE UNIQUE INDEX IF NOT EXISTS "push_subscriptions_user_id_subscription_key" ON "public"."push_subscriptions" USING "btree" ("user_id", "subscription");
-- #endregion
-- #endregion

-- #region task_templates table
CREATE TABLE IF NOT EXISTS "public"."task_templates" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "title" text NOT NULL,
    "default_description" text,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE "public"."task_templates" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."task_templates_tags" (
    "template_id" uuid NOT NULL REFERENCES public.task_templates(id) ON DELETE CASCADE,
    "tag_id" bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY ("template_id", "tag_id")
);
ALTER TABLE "public"."task_templates_tags" OWNER TO "postgres";
-- #endregion

-- #region TIME_SESSIONS and FLOWS tables
CREATE TABLE IF NOT EXISTS "public"."time_sessions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "mode" public.time_measurement_mode NOT NULL,
    "state" public.pomodoro_state NOT NULL DEFAULT 'idle',
    "started_at" timestamp with time zone,
    "finished_at" timestamp with time zone,
    "timelapse" integer NOT NULL DEFAULT 0,
    "toggle_timeline" jsonb,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE "public"."time_sessions" OWNER TO "postgres";

CREATE UNIQUE INDEX idx_unique_active_time_session ON "public"."time_sessions" ("user_id", "mode") WHERE state NOT IN ('finished', 'skipped');

CREATE TABLE IF NOT EXISTS "public"."flows" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "time_session_id" bigint NOT NULL REFERENCES public.time_sessions(id) ON DELETE CASCADE,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "jornada_bloque" text NOT NULL,
    "jornada_limit_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE "public"."flows" OWNER TO "postgres";
-- #endregion

-- #region OKR objectives and key_results
CREATE TYPE public.metric_category AS ENUM (
    'COUNT_ATOMIC',
    'TIME_INVESTMENT',
    'KNOWLEDGE_DENSITY',
    'QUALITY_SCORE'
);

CREATE TABLE IF NOT EXISTS "public"."objectives" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "title" text NOT NULL,
    "description" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."objectives" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."key_results" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "objective_id" uuid NOT NULL REFERENCES public.objectives(id) ON DELETE CASCADE,
    "title" text NOT NULL,
    "target_value" numeric NOT NULL,
    "current_value" numeric DEFAULT 0 NOT NULL,
    "metric_type" public.metric_category NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."key_results" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."key_result_tags" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "key_result_id" uuid NOT NULL REFERENCES public.key_results(id) ON DELETE CASCADE,
    "tag_id" bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    "weight" numeric DEFAULT 1.0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE ("key_result_id", "tag_id")
);
ALTER TABLE "public"."key_result_tags" OWNER TO "postgres";
-- #endregion

-- #region Zettelkasten notes table
CREATE TABLE IF NOT EXISTS "public"."notes" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "storage_path" text NOT NULL,
    "title" text,
    "frontmatter" jsonb,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE ("user_id", "storage_path")
);
ALTER TABLE "public"."notes" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."notes_tags" (
    "note_id" uuid NOT NULL REFERENCES public.notes(id) ON DELETE CASCADE,
    "tag_id" bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("note_id", "tag_id")
);
ALTER TABLE "public"."notes_tags" OWNER TO "postgres";
-- #endregion

-- #region scheduled_notifications table (declarative definition with action_type)
CREATE TABLE IF NOT EXISTS "public"."notification_templates" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" text NOT NULL,
    "title" text NOT NULL,
    "body" text NOT NULL,
    "icon" text,
    "link" text,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE "public"."notification_templates" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."scheduled_notifications" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "template_id" uuid REFERENCES public.notification_templates(id) ON DELETE SET NULL,
    "rrule" text,
    "scheduled_at" timestamp with time zone NOT NULL,
    "last_executed_at" timestamp with time zone,
    "timezone" text NOT NULL DEFAULT 'UTC',
    "payload_override" jsonb,
    "status" text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed')),
    "action_type" text DEFAULT 'NONE' CHECK (action_type IN ('NONE', 'CREATE_TASK', 'REVIEW_NOTE', 'CREATE_LOG', 'AI_ATOMIZE')),
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE "public"."scheduled_notifications" OWNER TO "postgres";

CREATE INDEX IF NOT EXISTS "ix_scheduled_notifications_scheduled_at" ON "public"."scheduled_notifications" USING btree ("scheduled_at");
CREATE INDEX IF NOT EXISTS "ix_scheduled_notifications_status" ON "public"."scheduled_notifications" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_scheduled_notifications_user_id" ON "public"."scheduled_notifications" USING btree ("user_id");

GRANT ALL ON TABLE "public"."scheduled_notifications" TO "anon";
GRANT ALL ON TABLE "public"."scheduled_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."scheduled_notifications" TO "service_role";

GRANT ALL ON TABLE "public"."notification_templates" TO "anon";
GRANT ALL ON TABLE "public"."notification_templates" TO "authenticated";
GRANT ALL ON TABLE "public"."notification_templates" TO "service_role";
-- #endregion

-- #region inbox_actions table
CREATE TABLE IF NOT EXISTS "public"."inbox_actions" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "source_notification_id" uuid REFERENCES public.scheduled_notifications(id) ON DELETE SET NULL,
    "title" text NOT NULL,
    "description" text,
    "action_type" text DEFAULT 'NONE'
        CHECK (action_type IN ('NONE', 'CREATE_TASK', 'REVIEW_NOTE', 'CREATE_LOG', 'AI_ATOMIZE', 'OKR_PROGRESS')),
    "action_payload" jsonb DEFAULT '{}',
    "status" text DEFAULT 'pending'
        CHECK (status IN ('pending', 'completed', 'dismissed')),
    "priority" int DEFAULT 1,
    "execution_count" int DEFAULT 0,
    "created_at" timestamptz DEFAULT now(),
    "completed_at" timestamptz
);
ALTER TABLE "public"."inbox_actions" OWNER TO "postgres";

CREATE INDEX IF NOT EXISTS "ix_inbox_actions_user_id" ON "public"."inbox_actions" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "ix_inbox_actions_status" ON "public"."inbox_actions" USING btree ("status");

GRANT ALL ON TABLE "public"."inbox_actions" TO "anon";
GRANT ALL ON TABLE "public"."inbox_actions" TO "authenticated";
GRANT ALL ON TABLE "public"."inbox_actions" TO "service_role";
-- #endregion

-- #region Grants for Note and OKR Tables
GRANT ALL ON TABLE "public"."objectives" TO "anon";
GRANT ALL ON TABLE "public"."objectives" TO "authenticated";
GRANT ALL ON TABLE "public"."objectives" TO "service_role";

GRANT ALL ON TABLE "public"."key_results" TO "anon";
GRANT ALL ON TABLE "public"."key_results" TO "authenticated";
GRANT ALL ON TABLE "public"."key_results" TO "service_role";

GRANT ALL ON TABLE "public"."key_result_tags" TO "anon";
GRANT ALL ON TABLE "public"."key_result_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."key_result_tags" TO "service_role";

GRANT ALL ON TABLE "public"."notes" TO "anon";
GRANT ALL ON TABLE "public"."notes" TO "authenticated";
GRANT ALL ON TABLE "public"."notes" TO "service_role";

GRANT ALL ON TABLE "public"."notes_tags" TO "anon";
GRANT ALL ON TABLE "public"."notes_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."notes_tags" TO "service_role";
-- #endregion
