

-- #region pomodoros table

CREATE TYPE "public"."pomodoro_state" AS ENUM (
    'current',
    'paused',
    'finished',
    'skipped',
    'idle'
);

ALTER TYPE "public"."pomodoro_state" OWNER TO "postgres";

CREATE TYPE "public"."pomodoro_type" AS ENUM (
    'focus',
    'break',
    'long_break'
);

ALTER TYPE "public"."pomodoro_type" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pomodoros" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "started_at" timestamp with time zone DEFAULT NULL,
    "expected_end" timestamp with time zone,
    "timelapse" integer DEFAULT 0 NOT NULL,
    "user_id" "uuid" NOT NULL,
    "state" "public"."pomodoro_state" DEFAULT 'idle'::"public"."pomodoro_state" NOT NULL,
    "finished_at" timestamp with time zone,
    "toggle_timeline" "jsonb",
    "cycle" bigint,
    "expected_duration" smallint DEFAULT '1500'::smallint NOT NULL,
    "type" "public"."pomodoro_type" DEFAULT 'focus'::"public"."pomodoro_type" NOT NULL
);

ALTER TABLE "public"."pomodoros" OWNER TO "postgres";
-- #endregion
-- #endregion

-- #region pomodoros_cycles table
CREATE TABLE IF NOT EXISTS "public"."pomodoros_cycles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "state" "public"."pomodoro_state",
    "user_id" "uuid",
    "required_tags" "text"[] DEFAULT '{focus,break,focus,long_break}'::"text"[]
);

ALTER TABLE "public"."pomodoros_cycles" OWNER TO "postgres";

ALTER TABLE "public"."pomodoros_cycles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pomodoros_cycles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
-- #endregion

-- #region pomodoros_tags table
CREATE TABLE IF NOT EXISTS "public"."pomodoros_tags" (
    "user_id" "uuid",
    "pomodoro" integer NOT NULL,
    "tag" integer NOT NULL
);


ALTER TABLE "public"."pomodoros_tags" OWNER TO "postgres";

-- #endregion


-- #region tags table
CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text",
    "label" "text" NOT NULL,
    "user_id" "uuid"
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
-- #endregion

-- #region tasks table
CREATE TYPE public.task_stage AS ENUM ('backlog', 'to_do', 'in_progress', 'done', 'archived');

CREATE TABLE IF NOT EXISTS "public"."tasks" (
    "id" "uuid" PRIMARY KEY DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "done" boolean DEFAULT false,
    "tag_id" integer,
    "pomodoro_id" integer,
    "archived" boolean DEFAULT false,
    "stage" public.task_stage DEFAULT 'backlog'::public.task_stage,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "done_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    "keep" boolean default false
);
ALTER TABLE "public"."tasks" OWNER TO "postgres";

-- #endregion

-- #region pomodoros_tasks table
create table public.pomodoros_tasks (
  id bigint generated by default as identity primary key,
  pomodoro_id bigint not null references public.pomodoros(id) on delete cascade,
  task_id uuid not null references public.tasks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (pomodoro_id, task_id)
);
-- #endregion

-- #region tasks_tags table
CREATE TABLE IF NOT EXISTS "public"."tasks_tags" (
    "user_id" "uuid",
    "task" "uuid" NOT NULL,
    "tag" integer NOT NULL
);
ALTER TABLE "public"."tasks_tags" OWNER TO "postgres";
-- #endregion

-- #region profiles table
CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "username" "text",
    "fullname" "text",
    "avatar_url" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "has_password" boolean DEFAULT false,
    "settings" "jsonb"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";
-- #endregion

-- #region api_keys table
CREATE TABLE IF NOT EXISTS "public"."api_keys" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"()
);

ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "api_keys_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."api_keys"
    ADD CONSTRAINT "api_keys_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."api_keys" OWNER TO "postgres";

-- #endregion






CREATE UNIQUE INDEX "profiles_username_idx" ON "public"."profiles" USING "btree" ("username");

CREATE UNIQUE INDEX "tags_label_system_idx" ON "public"."tags" USING "btree" ("label") WHERE ("user_id" IS NULL);

CREATE UNIQUE INDEX "tags_label_user_idx" ON "public"."tags" USING "btree" ("label", "user_id") WHERE ("user_id" IS NOT NULL);

CREATE UNIQUE INDEX "tags_type_system_idx" ON "public"."tags" USING "btree" ("type") WHERE ("user_id" IS NULL);



ALTER TABLE ONLY "public"."pomodoros_cycles"
    ADD CONSTRAINT "pomodoros_cycles_pkey" PRIMARY KEY ("id");






ALTER TABLE ONLY "public"."pomodoros_tags"
    ADD CONSTRAINT "pomodoros_tags_pkey" PRIMARY KEY ("tag", "pomodoro");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");





    

ALTER TABLE ONLY "public"."pomodoros_cycles"
    ADD CONSTRAINT "pomodoros_cycles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."pomodoros"
    ADD CONSTRAINT "pomodoros_cycle_fkey" FOREIGN KEY ("cycle") REFERENCES "public"."pomodoros_cycles"("id");



ALTER TABLE ONLY "public"."pomodoros_tags"
    ADD CONSTRAINT "pomodoros_tags_pomodoro_fkey" FOREIGN KEY ("pomodoro") REFERENCES "public"."pomodoros"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pomodoros_tags"
    ADD CONSTRAINT "pomodoros_tags_tag_fkey" FOREIGN KEY ("tag") REFERENCES "public"."tags"("id");



ALTER TABLE ONLY "public"."pomodoros_tags"
    ADD CONSTRAINT "pomodoros_tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");


ALTER TABLE ONLY "public"."tasks_tags"
    ADD CONSTRAINT "tasks_tags_pkey" PRIMARY KEY ("tag", "task");

ALTER TABLE ONLY "public"."tasks_tags"
    ADD CONSTRAINT "tasks_tags_task_fkey" FOREIGN KEY ("task") REFERENCES "public"."tasks"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tasks_tags"
    ADD CONSTRAINT "tasks_tags_tag_fkey" FOREIGN KEY ("tag") REFERENCES "public"."tags"("id");

ALTER TABLE ONLY "public"."tasks_tags"
    ADD CONSTRAINT "tasks_tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");


ALTER TABLE ONLY "public"."pomodoros"
    ADD CONSTRAINT "pomodoros_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_pomodoro_id_fkey" FOREIGN KEY ("pomodoro_id") REFERENCES "public"."pomodoros"("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



GRANT ALL ON TABLE "public"."pomodoros" TO "anon";
GRANT ALL ON TABLE "public"."pomodoros" TO "authenticated";
GRANT ALL ON TABLE "public"."pomodoros" TO "service_role";

GRANT ALL ON TABLE "public"."pomodoros_cycles" TO "anon";
GRANT ALL ON TABLE "public"."pomodoros_cycles" TO "authenticated";
GRANT ALL ON TABLE "public"."pomodoros_cycles" TO "service_role";


GRANT ALL ON SEQUENCE "public"."pomodoros_cycles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pomodoros_cycles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pomodoros_cycles_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pomodoros_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pomodoros_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pomodoros_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pomodoros_tags" TO "anon";
GRANT ALL ON TABLE "public"."pomodoros_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."pomodoros_tags" TO "service_role";

GRANT ALL ON TABLE "public"."tasks_tags" TO "anon";
GRANT ALL ON TABLE "public"."tasks_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tasks_tags" TO "service_role";


GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tasks" TO "anon";
GRANT ALL ON TABLE "public"."tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."tasks" TO "service_role";

-- #region documents table
CREATE TABLE IF NOT EXISTS "public"."documents" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "content" text,
    "metadata" jsonb,
    "embedding" extensions.vector(768)
);
ALTER TABLE "public"."documents" OWNER TO "postgres";
-- #endregion

-- #region n8n_chat_histories table
CREATE TABLE IF NOT EXISTS "public"."n8n_chat_histories" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "session_id" character varying(255) NOT NULL,
    "message" jsonb NOT NULL
);
ALTER TABLE "public"."n8n_chat_histories" OWNER TO "postgres";
-- #endregion

-- #region push_subscriptions table
CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "subscription" jsonb NOT NULL,
    "user_agent" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "idx_push_subscriptions_user_id" ON "public"."push_subscriptions" USING btree ("user_id");
-- #endregion

-- #region user_secrets table
CREATE TABLE IF NOT EXISTS "public"."user_secrets" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "secret_name" text NOT NULL,
    "encrypted_value" text NOT NULL,
    "iv" text NOT NULL,
    "tag" text NOT NULL,
    "active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE ("user_id", "secret_name")
);
ALTER TABLE "public"."user_secrets" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "idx_user_secrets_user_id" ON "public"."user_secrets" USING btree ("user_id");
-- #endregion

-- #region scheduled_notifications table (declarative definition with action_type)
CREATE TABLE IF NOT EXISTS "public"."notification_templates" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" text NOT NULL,
    "title" text NOT NULL,
    "body" text NOT NULL,
    "icon" text,
    "link" text,
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE "public"."notification_templates" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."scheduled_notifications" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "template_id" uuid REFERENCES public.notification_templates(id) ON DELETE SET NULL,
    "rrule" text,
    "scheduled_at" timestamp with time zone NOT NULL,
    "last_executed_at" timestamp with time zone,
    "timezone" text NOT NULL DEFAULT 'UTC',
    "payload_override" jsonb,
    "status" text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed')),
    "action_type" text DEFAULT 'NONE' CHECK (action_type IN ('NONE', 'CREATE_TASK', 'REVIEW_NOTE', 'CREATE_LOG', 'AI_ATOMIZE')),
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE "public"."scheduled_notifications" OWNER TO "postgres";

CREATE INDEX IF NOT EXISTS "ix_scheduled_notifications_scheduled_at" ON "public"."scheduled_notifications" USING btree ("scheduled_at");
CREATE INDEX IF NOT EXISTS "ix_scheduled_notifications_status" ON "public"."scheduled_notifications" USING btree ("status");
CREATE INDEX IF NOT EXISTS "ix_scheduled_notifications_user_id" ON "public"."scheduled_notifications" USING btree ("user_id");

GRANT ALL ON TABLE "public"."scheduled_notifications" TO "anon";
GRANT ALL ON TABLE "public"."scheduled_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."scheduled_notifications" TO "service_role";

GRANT ALL ON TABLE "public"."notification_templates" TO "anon";
GRANT ALL ON TABLE "public"."notification_templates" TO "authenticated";
GRANT ALL ON TABLE "public"."notification_templates" TO "service_role";
-- #endregion

-- #region inbox_actions table
CREATE TABLE IF NOT EXISTS "public"."inbox_actions" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "source_notification_id" uuid REFERENCES public.scheduled_notifications(id) ON DELETE SET NULL,
    "title" text NOT NULL,
    "description" text,
    "action_type" text DEFAULT 'NONE'
        CHECK (action_type IN ('NONE', 'CREATE_TASK', 'REVIEW_NOTE', 'CREATE_LOG', 'AI_ATOMIZE')),
    "action_payload" jsonb DEFAULT '{}',
    "status" text DEFAULT 'pending'
        CHECK (status IN ('pending', 'completed', 'dismissed')),
    "priority" int DEFAULT 1,
    "execution_count" int DEFAULT 0,
    "created_at" timestamptz DEFAULT now(),
    "completed_at" timestamptz
);
ALTER TABLE "public"."inbox_actions" OWNER TO "postgres";

CREATE INDEX IF NOT EXISTS "ix_inbox_actions_user_id" ON "public"."inbox_actions" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "ix_inbox_actions_status" ON "public"."inbox_actions" USING btree ("status");

GRANT ALL ON TABLE "public"."inbox_actions" TO "anon";
GRANT ALL ON TABLE "public"."inbox_actions" TO "authenticated";
GRANT ALL ON TABLE "public"."inbox_actions" TO "service_role";
-- #endregion
