revoke delete on table "public"."pomodoros-taggeds" from "anon";

revoke insert on table "public"."pomodoros-taggeds" from "anon";

revoke references on table "public"."pomodoros-taggeds" from "anon";

revoke select on table "public"."pomodoros-taggeds" from "anon";

revoke trigger on table "public"."pomodoros-taggeds" from "anon";

revoke truncate on table "public"."pomodoros-taggeds" from "anon";

revoke update on table "public"."pomodoros-taggeds" from "anon";

revoke delete on table "public"."pomodoros-taggeds" from "authenticated";

revoke insert on table "public"."pomodoros-taggeds" from "authenticated";

revoke references on table "public"."pomodoros-taggeds" from "authenticated";

revoke select on table "public"."pomodoros-taggeds" from "authenticated";

revoke trigger on table "public"."pomodoros-taggeds" from "authenticated";

revoke truncate on table "public"."pomodoros-taggeds" from "authenticated";

revoke update on table "public"."pomodoros-taggeds" from "authenticated";

revoke delete on table "public"."pomodoros-taggeds" from "service_role";

revoke insert on table "public"."pomodoros-taggeds" from "service_role";

revoke references on table "public"."pomodoros-taggeds" from "service_role";

revoke select on table "public"."pomodoros-taggeds" from "service_role";

revoke trigger on table "public"."pomodoros-taggeds" from "service_role";

revoke truncate on table "public"."pomodoros-taggeds" from "service_role";

revoke update on table "public"."pomodoros-taggeds" from "service_role";

alter table "public"."pomodoros-taggeds" drop constraint "pomodoros-taggeds_pomodoro_fkey";

alter table "public"."pomodoros-taggeds" drop constraint "pomodoros-taggeds_tag_fkey";

alter table "public"."pomodoros-taggeds" drop constraint "pomodoros-taggeds_pkey";

drop index if exists "public"."pomodoros-taggeds_pkey";

drop table "public"."pomodoros-taggeds";


  create table "public"."pomodoros_cycles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "state" public."pomodoro-state",
    "user_id" uuid,
    "required_tags" text[] default '{focus,break,focus,long-break}'::text[]
      );


alter table "public"."pomodoros_cycles" enable row level security;


  create table "public"."pomodoros_tags" (
    "user_id" uuid,
    "pomodoro" integer not null,
    "tag" integer not null
      );


alter table "public"."pomodoros_tags" enable row level security;

alter table "public"."pomodoros" drop column "duration";

alter table "public"."pomodoros" add column "cycle" bigint;

alter table "public"."pomodoros" add column "expected_duration" smallint;

CREATE UNIQUE INDEX "pomodoro-cycles_pkey" ON public.pomodoros_cycles USING btree (id);

CREATE UNIQUE INDEX pomodoros_tags_pkey ON public.pomodoros_tags USING btree (tag, pomodoro);

alter table "public"."pomodoros_cycles" add constraint "pomodoro-cycles_pkey" PRIMARY KEY using index "pomodoro-cycles_pkey";

alter table "public"."pomodoros_tags" add constraint "pomodoros_tags_pkey" PRIMARY KEY using index "pomodoros_tags_pkey";

alter table "public"."pomodoros" add constraint "pomodoros_cycle_fkey" FOREIGN KEY (cycle) REFERENCES public.pomodoros_cycles(id) not valid;

alter table "public"."pomodoros" validate constraint "pomodoros_cycle_fkey";

alter table "public"."pomodoros_cycles" add constraint "pomodoro-cycles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."pomodoros_cycles" validate constraint "pomodoro-cycles_user_id_fkey";

alter table "public"."pomodoros_tags" add constraint "pomodoros_tags_pomodoro_fkey" FOREIGN KEY (pomodoro) REFERENCES public.pomodoros(id) not valid;

alter table "public"."pomodoros_tags" validate constraint "pomodoros_tags_pomodoro_fkey";

alter table "public"."pomodoros_tags" add constraint "pomodoros_tags_tag_fkey" FOREIGN KEY (tag) REFERENCES public.tags(id) not valid;

alter table "public"."pomodoros_tags" validate constraint "pomodoros_tags_tag_fkey";

alter table "public"."pomodoros_tags" add constraint "pomodoros_tags_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."pomodoros_tags" validate constraint "pomodoros_tags_user_id_fkey";

grant delete on table "public"."pomodoros_cycles" to "anon";

grant insert on table "public"."pomodoros_cycles" to "anon";

grant references on table "public"."pomodoros_cycles" to "anon";

grant select on table "public"."pomodoros_cycles" to "anon";

grant trigger on table "public"."pomodoros_cycles" to "anon";

grant truncate on table "public"."pomodoros_cycles" to "anon";

grant update on table "public"."pomodoros_cycles" to "anon";

grant delete on table "public"."pomodoros_cycles" to "authenticated";

grant insert on table "public"."pomodoros_cycles" to "authenticated";

grant references on table "public"."pomodoros_cycles" to "authenticated";

grant select on table "public"."pomodoros_cycles" to "authenticated";

grant trigger on table "public"."pomodoros_cycles" to "authenticated";

grant truncate on table "public"."pomodoros_cycles" to "authenticated";

grant update on table "public"."pomodoros_cycles" to "authenticated";

grant delete on table "public"."pomodoros_cycles" to "service_role";

grant insert on table "public"."pomodoros_cycles" to "service_role";

grant references on table "public"."pomodoros_cycles" to "service_role";

grant select on table "public"."pomodoros_cycles" to "service_role";

grant trigger on table "public"."pomodoros_cycles" to "service_role";

grant truncate on table "public"."pomodoros_cycles" to "service_role";

grant update on table "public"."pomodoros_cycles" to "service_role";

grant delete on table "public"."pomodoros_tags" to "anon";

grant insert on table "public"."pomodoros_tags" to "anon";

grant references on table "public"."pomodoros_tags" to "anon";

grant select on table "public"."pomodoros_tags" to "anon";

grant trigger on table "public"."pomodoros_tags" to "anon";

grant truncate on table "public"."pomodoros_tags" to "anon";

grant update on table "public"."pomodoros_tags" to "anon";

grant delete on table "public"."pomodoros_tags" to "authenticated";

grant insert on table "public"."pomodoros_tags" to "authenticated";

grant references on table "public"."pomodoros_tags" to "authenticated";

grant select on table "public"."pomodoros_tags" to "authenticated";

grant trigger on table "public"."pomodoros_tags" to "authenticated";

grant truncate on table "public"."pomodoros_tags" to "authenticated";

grant update on table "public"."pomodoros_tags" to "authenticated";

grant delete on table "public"."pomodoros_tags" to "service_role";

grant insert on table "public"."pomodoros_tags" to "service_role";

grant references on table "public"."pomodoros_tags" to "service_role";

grant select on table "public"."pomodoros_tags" to "service_role";

grant trigger on table "public"."pomodoros_tags" to "service_role";

grant truncate on table "public"."pomodoros_tags" to "service_role";

grant update on table "public"."pomodoros_tags" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."pomodoros_cycles"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable insert for users based on user_id"
  on "public"."pomodoros_cycles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."pomodoros_cycles"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for authenticated users only"
  on "public"."pomodoros_tags"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable insert for users based on user_id"
  on "public"."pomodoros_tags"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."pomodoros_tags"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."tags"
  as permissive
  for select
  to public
using (true);



