-- TIME/FLOW Architecture: time_sessions, flows tables, and time_measurement_mode enum

-- 1. Create enum for measurement modes
CREATE TYPE public.time_measurement_mode AS ENUM ('pomodoro', 'flow');

-- 2. Create time_sessions table (parent entity)
CREATE TABLE public.time_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  mode public.time_measurement_mode NOT NULL,
  state public.pomodoro_state NOT NULL DEFAULT 'idle',
  started_at timestamptz,
  finished_at timestamptz,
  timelapse integer NOT NULL DEFAULT 0,
  toggle_timeline jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. Create flows table (child entity)
CREATE TABLE public.flows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time_session_id bigint NOT NULL REFERENCES public.time_sessions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  jornada_bloque text NOT NULL,
  jornada_limit_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. Add time_session_id FK to pomodoros
ALTER TABLE public.pomodoros
  ADD COLUMN time_session_id bigint REFERENCES public.time_sessions(id) ON DELETE SET NULL;

-- 5. Unique constraint: max 1 active session per user+mode
CREATE UNIQUE INDEX idx_unique_active_time_session
  ON public.time_sessions (user_id, mode)
  WHERE state NOT IN ('finished', 'skipped');

-- 6. RLS for time_sessions
ALTER TABLE public.time_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own time_sessions"
  ON public.time_sessions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own time_sessions"
  ON public.time_sessions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own time_sessions"
  ON public.time_sessions FOR UPDATE
  USING (auth.uid() = user_id);

-- 7. RLS for flows
ALTER TABLE public.flows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own flows"
  ON public.flows FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own flows"
  ON public.flows FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own flows"
  ON public.flows FOR UPDATE
  USING (auth.uid() = user_id);
