/**
 * Type helpers for Supabase autogenerated types.
 *
 * Use these instead of raw `Tables<"...">` for better IDE navigation (F12)
 * and hover previews that show actual column definitions.
 */
import type { Database } from "./database.types";

/** Expands a type so the IDE shows all properties on hover/F12 */
type Prettify<T> = { [K in keyof T]: T[K] } & {};

// ─── Table Row Types ────────────────────────────────────────
export type TaskRow = Prettify<Database["public"]["Tables"]["tasks"]["Row"]>;
export type TagRow = Prettify<Database["public"]["Tables"]["tags"]["Row"]>;
export type ProfileRow = Prettify<
  Database["public"]["Tables"]["profiles"]["Row"]
>;
export type PomodoroRow = Prettify<
  Database["public"]["Tables"]["pomodoros"]["Row"]
>;

// ─── Insert Types ───────────────────────────────────────────
export type TaskInsert = Prettify<
  Database["public"]["Tables"]["tasks"]["Insert"]
>;
export type TagInsert = Prettify<
  Database["public"]["Tables"]["tags"]["Insert"]
>;

// ─── Update Types ───────────────────────────────────────────
export type TaskUpdate = Prettify<
  Database["public"]["Tables"]["tasks"]["Update"]
>;
export type TagUpdate = Prettify<
  Database["public"]["Tables"]["tags"]["Update"]
>;

// ─── Enum Types ─────────────────────────────────────────────
export type TaskStage = Database["public"]["Enums"]["task_stage"];
export const TaskStage = {
  BACKLOG: "backlog",
  TO_DO: "to_do",
  IN_PROGRESS: "in_progress",
  DONE: "done",
  ARCHIVED: "archived",
} as const;
export type PomodoroType = Database["public"]["Enums"]["pomodoro_type"];
export type PomodoroState = Database["public"]["Enums"]["pomodoro_state"];
